
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'cartiga_dbt_model'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'cartiga_dbt_model'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

#target-path: "target"  # directory which will store compiled SQL files
target-path: /usr/local/airflow/tmp/target
log-path: /usr/local/airflow/tmp/logs
module-path: /usr/local/airflow/tmp/dbt_packages
clean-targets:         # directories to be removed by `dbt clean`
  - "/usr/local/airflow/tmp/target"
  - "/usr/local/airflow/tmp/dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  cartiga_dbt_model:
    # Config indicated by + and applies to all files under models/example/
    cartiga_silver:
      +schema: silver
      +materialized: table
      accounts:
        +materialized: table
    
    cartiga_gold_mart:
        +materialized: view
