cartiga_dbt_model:
  outputs:
    dev:
      host: dbc-45e2e7e5-9747.cloud.databricks.com
      http_path: /sql/1.0/endpoints/7d7fab46ebd21483
      schema: momentumfunding123nsf0916
      threads: 1
      token: dapi316d47b8b5d9ef261345b1a94b29d63f
      type: databricks
      target-path: /usr/local/airflow/tmp/target
      log-path: /usr/local/airflow/tmp/logs
  target: dev
