# .circleci/config.yml
version: 2
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
  build:
    working_directory: ~/airflow-dags-ci
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: echo "A first build"
      - run: mkdir -p my_workspace
  
  test:
    working_directory: ~/airflow-dags-ci
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: echo "A first test"

workflows:
  version: 2
  buld_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
