with stg_contact as (
    select * from {{ source("cartiga_bronze","contact") }}
),

stg_record_type as (
    select * from {{ source("cartiga_bronze","record_type") }}
),

silver_contact as (
    select 
    c.record_type_id,
    rt.developer_name,
    rt.created_date as RecordCreatedDate,
    rt.created_by_id as RecordCreatedId,
    c.first_name,
    c.middle_name,
    c.assistant_name, 
    c.created_date as ContactCreatedDate, 
    rt.description as RecordDescr, 
    c.last_name, 
    rt.name as RecordName, 
    c.reports_to_id, 
    rt.sobject_type, 
    c.created_by_id, 
    c.department, 
    c.home_phone, 
    rt.is_person_type, 
    c.other_phone, 
    rt.system_modstamp as RecordSysModstamp, 
    c.account_id, 
    c.active_c, 
    c.birthdate, 
    c.description as ContactDescr, 
    c.do_not_call, 
    rt.is_active, 
    rt.last_modified_date as RecordLastModifiedDate, 
    c.lead_source, 
    c.mobile_phone, 
    c.name as ContactName, 
    c.other_state, 
    rt._fivetran_synced as RecordFivetranSynced, 
    c.account_manager_c, 
    c.assistant_phone, 
    c.do_not_fund_c, 
    c.email_bounced_date, 
    c.gender_c, 
    rt.id as RecordId, 
    c.laserca_pin_c, 
    c.laserca_tin_c, 
    c.last_cuupdate_date, 
    c.last_viewed_date, 
    c.other_city, 
    c.other_country, 
    c.other_latitude, 
    c.other_longitude, 
    c.other_street, 
    c.phone, 
    c.photo_url, 
    c.system_modstamp as ContactSysModstamp, 
    rt._fivetran_deleted, 
    c.bar_status_c, 
    c.broker_c, 
    c.email, 
    c.is_deleted, 
    c.laserca_file_number_c, 
    c.laserca_home_state_c, 
    c.laserca_home_zip_c, 
    c.last_activity_date, 
    c.last_curequest_date, 
    c.last_modified_date as ContactLastModifiedDate, 
    c.last_referenced_date, 
    c.mailing_state,
    rt.namespace_prefix, 
    c.other_postal_code, 
    c.owner_id, 
    c.previous_law_firm_c, 
    c.rh_2_describe_c, 
    c.salutation, 
    c.title, 
    c._fivetran_synced as ContactFivetranSynced, 
    rt.business_process_id, 
    c.fax, 
    c.has_opted_out_of_fax, 
    c.id, 
    c.ims_check_date_c, 
    c.individual_id, 
    c.is_email_bounced, 
    c.jigsaw, c.languages_c, 
    c.laserca_home_city_c, 
    rt.last_modified_by_id as RecordLastModifiedId, 
    c.mailing_city, 
    c.mailing_country, 
    c.mailing_latitude, 
    c.mailing_longitude, 
    c.mailing_street, 
    c.master_record_id, 
    c.rh_2_integer_test_c, 
    c.ssn_c, 
    c.email_bounced_reason, 
    c.has_opted_out_of_email, 
    c.is_person_account, 
    c.jigsaw_contact_id, 
    c.mailing_postal_code, 
    c.other_geocode_accuracy, 
    c.rh_2_currency_test_c, c.suffix, 
    c.date_of_last_visit_c, 
    c.do_not_fund_start_date_c, 
    c.external_attorney_id_c, 
    c.laserca_credit_bureau_c, 
    c.laserca_home_address_c, 
    c.laserca_home_country_c, 
    c.last_modified_by_id as ContactLastModifiedId, 
    c.special_instructions_c, 
    c.do_not_fund_reason_s_c, 
    c.laserca_applicant_id_c, 
    c.laserca_co_applicant_name_c, 
    c.laserca_middle_initial_c, 
    c.legal_staff_function_c, 
    c.plaintiff_birthdate_c, 
    c.attorney_associated_to_c, 
    c.bar_status_checked_by_c, 
    c.cartiga_business_unit_c, 
    c.historical_old_record_id_c, 
    c.attorney_servicing_email_c, 
    c.attorney_specialization_c, 
    c.external_legal_staff_id_c, 
    c.laserca_special_option_c, 
    c.mailing_geocode_accuracy, 
    c.bar_status_expiration_date_c, 
    c.laserca_co_applicant_dob_c, 
    c.laserca_co_applicant_ssn_c, 
    c.outside_account_exec_owner_c, 
    c.external_medical_employee_c, 
    c.laserca_pull_credit_report_c, 
    c.plaintiff_birthdate_text_c, 
    c.total_of_court_cases_impaired_c, 
    c.attorney_last_servicing_sent_c, 
    c.contact_from_sales_rep_only_c, 
    c.laserca_co_applicant_last_name_c, 
    c.total_of_fundings_attorney_c, 
    c.total_repaid_amount_attorney_c, 
    c.attorney_first_servicing_sent_c, 
    c.indiana_ownership_amount_3_c, 
    c.laserca_request_credit_bureau_c, 
    c.laserca_social_security_number_c, 
    c.total_repaid_amount_repaid_only_c, 
    c.account_exec_owner_commission_c, 
    c.attorney_servicing_outstanding_c, 
    c.et_4_ae_5_mobile_country_code_c, 
    c.repaid_principal_amount_attorney_c, 
    c.total_of_funding_paid_in_full_c, 
    c.disclosure_letters_instructions_c, 
    c.driver_s_license_id_received_date_c, 
    c.first_application_date_attorney_c, 
    c.first_disbursement_date_attorney_c, 
    c.funded_amount_all_time_attorney_c, c.last_application_date_attorney_c, 
    c.total_due_at_write_off_attorney_c, 
    c.total_of_applications_approved_c, 
    c.total_of_applications_attorney_c, 
    c.total_of_open_fundings_attorney_c, 
    c.amount_due_at_repayment_attorney_c, 
    c.bypass_new_attorney_validation_c, 
    c.et_4_ae_5_has_opted_out_of_mobile_c, 
    c.funding_total_funded_amount_open_c, 
    c.has_opted_out_of_servicing_email_c, 
    c.total_open_amount_due_now_attorney_c, 
    c.number_of_applications_declined_c, 
    c.closed_cases_funded_amount_attorney_c, 
    c.laserca_bypass_duplicate_detection_c, 
    c.ttl_written_off_apprvd_princ_attorney_c, 
    c.calculated_attorney_marketing_segment_c, 
    c.total_of_fundings_with_partial_payment_c, 
    c.total_repaid_due_at_repayment_attorney_c, 
    c.attorney_s_marketing_segment_override_c, 
    c.laserca_pull_equifax_decision_power_c, 
    c.outside_account_exec_owner_commission_c, 
    c.total_of_funding_paid_in_full_attorney_c, 
    c.total_of_fundings_written_off_attorney_c,
    c.laserca_co_applicant_social_security_number_c
    from stg_contact c
    left join stg_record_type rt on rt.id = c.record_type_id
    where rt.name == 'Law Firm Personnel'
)

select * from silver_contact